ALTER TYPE "StepUpPurpose" ADD VALUE IF NOT EXISTS 'LEAVE_BALANCE_MANUAL_ADJUSTMENT';

ALTER TYPE "AuditAction" ADD VALUE IF NOT EXISTS 'LEAVE_BALANCE_MANUAL_ADJUSTMENT_CREATED';
ALTER TYPE "AuditAction" ADD VALUE IF NOT EXISTS 'LEAVE_BALANCE_MANUAL_ADJUSTMENT_BLOCKED';
