ALTER TYPE "LeaveGrantSource" ADD VALUE IF NOT EXISTS 'MONTHLY_ACCRUAL';
ALTER TYPE "LeaveGrantSource" ADD VALUE IF NOT EXISTS 'ANNUAL_FIRST_YEAR';
ALTER TYPE "LeaveGrantSource" ADD VALUE IF NOT EXISTS 'ANNUAL_FISCAL_YEAR';

ALTER TYPE "LeaveLedgerSource" ADD VALUE IF NOT EXISTS 'MONTHLY_ACCRUAL';
ALTER TYPE "LeaveLedgerSource" ADD VALUE IF NOT EXISTS 'ANNUAL_FIRST_YEAR';
ALTER TYPE "LeaveLedgerSource" ADD VALUE IF NOT EXISTS 'ANNUAL_FISCAL_YEAR';

ALTER TABLE "LeaveGrant" ADD COLUMN "idempotencyKey" TEXT;
CREATE UNIQUE INDEX "LeaveGrant_idempotencyKey_key" ON "LeaveGrant"("idempotencyKey");
