ALTER TYPE "AuditAction" ADD VALUE IF NOT EXISTS 'INVITATION_VERIFICATION_CODE_CREATED';
ALTER TYPE "AuditAction" ADD VALUE IF NOT EXISTS 'INVITATION_VERIFICATION_CODE_FAILED';
ALTER TYPE "AuditAction" ADD VALUE IF NOT EXISTS 'INVITATION_VERIFICATION_CODE_CONSUMED';
ALTER TYPE "AuditAction" ADD VALUE IF NOT EXISTS 'INVITATION_VERIFICATION_CODE_REVOKED';
ALTER TYPE "AuditAction" ADD VALUE IF NOT EXISTS 'INVITATION_REISSUED_WITH_VERIFICATION_CODE';
ALTER TYPE "AuditAction" ADD VALUE IF NOT EXISTS 'OWNER_INVITATION_REISSUED_WITH_VERIFICATION_CODE';

ALTER TABLE "Invitation"
  ADD COLUMN "verificationCodeHash" TEXT,
  ADD COLUMN "verificationCodeExpiresAt" TIMESTAMP(3),
  ADD COLUMN "verificationCodeConsumedAt" TIMESTAMP(3),
  ADD COLUMN "verificationCodeRevokedAt" TIMESTAMP(3),
  ADD COLUMN "verificationCodeAttemptCount" INTEGER NOT NULL DEFAULT 0,
  ADD COLUMN "verificationCodeMaxAttempts" INTEGER NOT NULL DEFAULT 5;

CREATE INDEX "Invitation_verificationCodeExpiresAt_idx" ON "Invitation"("verificationCodeExpiresAt");
