ALTER TYPE "AuditAction" ADD VALUE IF NOT EXISTS 'EXTERNAL_EMAIL_SENT';
ALTER TYPE "AuditAction" ADD VALUE IF NOT EXISTS 'EXTERNAL_EMAIL_FAILED';
ALTER TYPE "AuditAction" ADD VALUE IF NOT EXISTS 'EXTERNAL_SLACK_SENT';
ALTER TYPE "AuditAction" ADD VALUE IF NOT EXISTS 'EXTERNAL_SLACK_FAILED';
ALTER TYPE "AuditAction" ADD VALUE IF NOT EXISTS 'INVITATION_EMAIL_SENT';
ALTER TYPE "AuditAction" ADD VALUE IF NOT EXISTS 'INVITATION_EMAIL_FAILED';
