ALTER TYPE "StepUpPurpose" ADD VALUE IF NOT EXISTS 'SESSION_ADMIN';
ALTER TYPE "StepUpPurpose" ADD VALUE IF NOT EXISTS 'POLICY_CHANGE';

ALTER TYPE "AuditAction" ADD VALUE IF NOT EXISTS 'STEP_UP_VERIFICATION_CONSUMED';
ALTER TYPE "AuditAction" ADD VALUE IF NOT EXISTS 'ROLE_CHANGE_BLOCKED';
ALTER TYPE "AuditAction" ADD VALUE IF NOT EXISTS 'LAST_OWNER_PROTECTION_TRIGGERED';
ALTER TYPE "AuditAction" ADD VALUE IF NOT EXISTS 'SELF_ROLE_CHANGE_BLOCKED';
ALTER TYPE "AuditAction" ADD VALUE IF NOT EXISTS 'EMPLOYEE_DEACTIVATION_BLOCKED';
ALTER TYPE "AuditAction" ADD VALUE IF NOT EXISTS 'EMPLOYEE_DEACTIVATED_WITH_STEP_UP';
ALTER TYPE "AuditAction" ADD VALUE IF NOT EXISTS 'INVITATION_REISSUED_WITH_STEP_UP';
ALTER TYPE "AuditAction" ADD VALUE IF NOT EXISTS 'REPORT_EXPORT_STEP_UP_REQUIRED';
ALTER TYPE "AuditAction" ADD VALUE IF NOT EXISTS 'POLICY_CHANGE_WITH_STEP_UP';

ALTER TABLE "StepUpVerification" ADD COLUMN IF NOT EXISTS "revokedAt" TIMESTAMP(3);
ALTER TABLE "StepUpVerification" ALTER COLUMN "verifiedAt" SET DEFAULT CURRENT_TIMESTAMP;

CREATE INDEX IF NOT EXISTS "StepUpVerification_revokedAt_idx" ON "StepUpVerification"("revokedAt");
