-- AlterEnum
ALTER TYPE "AuditAction" ADD VALUE 'LEAVE_REQUEST_AUTO_CONFIRMED_AFTER_START_DATE';
ALTER TYPE "AuditAction" ADD VALUE 'AUTO_CONFIRM_PAST_START_LEAVES_RUN';
ALTER TYPE "AuditAction" ADD VALUE 'AUTO_CONFIRM_PAST_START_LEAVES_DRY_RUN';

-- AlterTable
ALTER TABLE "ApprovalPolicy" ALTER COLUMN "autoConfirmTiming" SET DEFAULT 'AFTER_START_DATE';
