ALTER TYPE "LeaveLedgerSource" ADD VALUE IF NOT EXISTS 'IMPORT_RECONCILIATION_ADJUSTMENT';

ALTER TYPE "AuditAction" ADD VALUE IF NOT EXISTS 'LEAVE_IMPORT_RECONCILIATION_DIFF_FOUND';
ALTER TYPE "AuditAction" ADD VALUE IF NOT EXISTS 'LEAVE_IMPORT_RECONCILIATION_ADJUSTMENT_CREATED';
ALTER TYPE "AuditAction" ADD VALUE IF NOT EXISTS 'LEAVE_IMPORT_RECONCILIATION_ADJUSTMENT_BLOCKED';
