ALTER TYPE "NotificationType" ADD VALUE IF NOT EXISTS 'LEAVE_REQUEST_CREATED';
ALTER TYPE "NotificationType" ADD VALUE IF NOT EXISTS 'LEAVE_REQUEST_APPROVED';
ALTER TYPE "NotificationType" ADD VALUE IF NOT EXISTS 'LEAVE_REQUEST_REJECTED';
ALTER TYPE "NotificationType" ADD VALUE IF NOT EXISTS 'LEAVE_REQUEST_CANCELLED';
ALTER TYPE "NotificationType" ADD VALUE IF NOT EXISTS 'ANNUAL_LEAVE_EXPIRING';
ALTER TYPE "NotificationType" ADD VALUE IF NOT EXISTS 'ATTENDANCE_MISSING_CHECK_OUT';
ALTER TYPE "NotificationType" ADD VALUE IF NOT EXISTS 'ATTENDANCE_CHANGE_REQUEST_CREATED';
ALTER TYPE "NotificationType" ADD VALUE IF NOT EXISTS 'ATTENDANCE_CHANGE_REQUEST_APPROVED';
ALTER TYPE "NotificationType" ADD VALUE IF NOT EXISTS 'ATTENDANCE_CHANGE_REQUEST_REJECTED';
ALTER TYPE "NotificationType" ADD VALUE IF NOT EXISTS 'INVITATION_EXPIRING';
ALTER TYPE "NotificationType" ADD VALUE IF NOT EXISTS 'SECURITY_EVENT';
ALTER TYPE "NotificationType" ADD VALUE IF NOT EXISTS 'PASSWORD_RESET';

ALTER TYPE "NotificationPriority" ADD VALUE IF NOT EXISTS 'CRITICAL';

ALTER TYPE "AuditAction" ADD VALUE IF NOT EXISTS 'NOTIFICATION_ARCHIVED';
ALTER TYPE "AuditAction" ADD VALUE IF NOT EXISTS 'NOTIFICATION_DELETED';

ALTER TABLE "Notification" ADD COLUMN IF NOT EXISTS "archivedAt" TIMESTAMP(3);
ALTER TABLE "Notification" ADD COLUMN IF NOT EXISTS "deletedAt" TIMESTAMP(3);

CREATE INDEX IF NOT EXISTS "Notification_archivedAt_idx" ON "Notification"("archivedAt");
CREATE INDEX IF NOT EXISTS "Notification_deletedAt_idx" ON "Notification"("deletedAt");
