ALTER TYPE "AuditAction" ADD VALUE IF NOT EXISTS 'USER_ROLE_CHANGED';
ALTER TYPE "AuditAction" ADD VALUE IF NOT EXISTS 'USER_TEAM_CHANGED';
ALTER TYPE "AuditAction" ADD VALUE IF NOT EXISTS 'TEAM_LEAD_ASSIGNED';
ALTER TYPE "AuditAction" ADD VALUE IF NOT EXISTS 'TEAM_LEAD_REMOVED';
ALTER TYPE "AuditAction" ADD VALUE IF NOT EXISTS 'PERMISSION_PREVIEW_VIEWED';
ALTER TYPE "AuditAction" ADD VALUE IF NOT EXISTS 'PERMISSION_CHANGE_BLOCKED';
