CREATE TYPE "StepUpPurpose" AS ENUM (
  'OWNER_ROLE_CHANGE',
  'ROLE_CHANGE',
  'EMPLOYEE_DEACTIVATION',
  'INVITATION_REISSUE',
  'REPORT_EXPORT',
  'SECURITY_ADMIN'
);

ALTER TYPE "AuditAction" ADD VALUE IF NOT EXISTS 'STEP_UP_VERIFICATION_SUCCEEDED';
ALTER TYPE "AuditAction" ADD VALUE IF NOT EXISTS 'STEP_UP_VERIFICATION_FAILED';
ALTER TYPE "AuditAction" ADD VALUE IF NOT EXISTS 'OWNER_ROLE_GRANTED';
ALTER TYPE "AuditAction" ADD VALUE IF NOT EXISTS 'OWNER_ROLE_REVOKED';
ALTER TYPE "AuditAction" ADD VALUE IF NOT EXISTS 'SESSION_REVOKED_BY_ADMIN';
ALTER TYPE "AuditAction" ADD VALUE IF NOT EXISTS 'SECURITY_SETTING_CHANGED';
ALTER TYPE "AuditAction" ADD VALUE IF NOT EXISTS 'SUSPICIOUS_LOGIN_DETECTED';
ALTER TYPE "AuditAction" ADD VALUE IF NOT EXISTS 'CSRF_BLOCKED';
ALTER TYPE "AuditAction" ADD VALUE IF NOT EXISTS 'UNAUTHORIZED_ACCESS_BLOCKED';

CREATE TABLE "StepUpVerification" (
  "id" TEXT NOT NULL,
  "userId" TEXT NOT NULL,
  "purpose" "StepUpPurpose" NOT NULL,
  "verifiedAt" TIMESTAMP(3) NOT NULL,
  "expiresAt" TIMESTAMP(3) NOT NULL,
  "consumedAt" TIMESTAMP(3),
  "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,

  CONSTRAINT "StepUpVerification_pkey" PRIMARY KEY ("id")
);

CREATE INDEX "StepUpVerification_userId_idx" ON "StepUpVerification"("userId");
CREATE INDEX "StepUpVerification_purpose_idx" ON "StepUpVerification"("purpose");
CREATE INDEX "StepUpVerification_expiresAt_idx" ON "StepUpVerification"("expiresAt");
CREATE INDEX "StepUpVerification_consumedAt_idx" ON "StepUpVerification"("consumedAt");

ALTER TABLE "StepUpVerification"
  ADD CONSTRAINT "StepUpVerification_userId_fkey"
  FOREIGN KEY ("userId") REFERENCES "User"("id") ON DELETE CASCADE ON UPDATE CASCADE;
